### PR TITLE
added render pause/resume functionality

### PR DESCRIPTION
**Pull request by der-On**

### CODE REVIEW

**Comment by AVGP** [comment]
Sweet idea! Thank you

**Comment by AVGP** [comment]
If you don't mind, tho, I'll simplify the functions to `.pause`, `.resume` and `isPaused`

**Comment by AVGP** [comment]
Just landed as 2.0.0: https://github.com/AVGP/three-world/releases/tag/2.0.0

**Comment by der-On** [comment]
Great! I currently use it to keep the GPU low while coding having the window opened in the browser aside. ;)

**Pull request merged**
